services:

  robocup_demo:
    ports:
      - "1666:1666"  
      - "1667:1667"
    container_name: robocup_demo_v2
    image: robocup_public:1.0
    network_mode: host
    runtime: nvidia
    tty: true
    build:
      context: .
      dockerfile: dockerfile.jetson
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/home/booster/.Xauthority
      - FASTRTPS_DEFAULT_PROFILES_FILE=/home/booster/booster_ws/configs/fastdds.xml
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/home/booster/.Xauthority:rw
      - ./src:/home/booster/booster_ws/src
      - ./configs:/home/booster/booster_ws/configs
      - ./scripts:/home/booster/booster_ws/scripts
    command: >
      bash -c "
        source /opt/ros/humble/setup.bash &&
        source install/setup.bash &&
        ./scripts/start.sh &&
        echo DONE! &&
        tail -f /dev/null
      "
  booster_brain:
    container_name: booster_brain
    build:
      context: .
      dockerfile: dockerfile
    image: robocup_demo:2.0
    runtime: nvidia
    network_mode: host
    ipc: host
    pid: host
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - XAUTHORITY=/home/booster/.Xauthority
      - FASTRTPS_DEFAULT_PROFILES_FILE=/home/booster/booster_ws/configs/fastdds.xml
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/home/booster/.Xauthority:rw
      - ./src:/home/booster/booster_ws/src
      - ./scripts:/home/booster/booster_ws/scripts
      - ./configs:/home/booster/booster_ws/configs
    stdin_open: true
    tty: true
    command: >
      bash -c "
        source /opt/ros/humble/setup.bash &&
        ./scripts/sim_start.sh &&
        tail -f /dev/null
      "
